AWSTemplateFormatVersion: '2010-09-09'
Description: FMS notification channel test.
Resources:
  NotificationChannel:
    Type: AWS::FMS::NotificationChannel
    Properties:
      SnsRoleName: !ImportValue NotificationChannelCreationRole
      SnsTopicArn: !ImportValue SnsTopicArn
  WaiterCustomResource:
    Type: "AWS::CloudFormation::CustomResource"
    DeletionPolicy: Retain
    Properties:
      ServiceToken: !ImportValue LambdaWaiter
      WaitSeconds: 600
