AWSTemplateFormatVersion: '2010-09-09'
Description: FMS WAFv2 policy update test.
Resources:
  CanaryPolicyWAFv2:
    Type: AWS::FMS::Policy
    Properties:
      ExcludeResourceTags: false
      PolicyName: CanaryPolicyWAFv2UPDATE
      RemediationEnabled: false
      ResourcesCleanUp: false
      DeleteAllPolicyResources: false
      ResourceType: AWS::ElasticLoadBalancingV2::LoadBalancer
      ResourceTags:
        - Key: test1
          Value: test1
        - Key: test2
          Value: test2
      Tags:
        - Key: test1
          Value: test1
        - Key: test2
          Value: test2
      SecurityServicePolicyData:
        Type: WAFV2
        ManagedServiceData: '
          {
            "type": "WAFV2",
            "preProcessRuleGroups": [
              {
                "ruleGroupArn": null,
                "overrideAction": {
                  "type": "NONE"
                },
                "managedRuleGroupIdentifier": {
                  "version": null,
                  "vendorName": "AWS",
                  "managedRuleGroupName": "AWSManagedRulesAmazonIpReputationList"
                },
                "ruleGroupType": "ManagedRuleGroup",
                "excludeRules": [],
                "sampledRequestsEnabled": true
              }
            ],
            "postProcessRuleGroups": [],
            "defaultAction": {
              "type": "ALLOW"
            },
            "overrideCustomerWebACLAssociation": false,
            "loggingConfiguration": null,
            "sampledRequestsEnabledForDefaultActions": false
          }'
  WaiterCustomResource:
    Type: "AWS::CloudFormation::CustomResource"
    DeletionPolicy: Retain
    Properties:
      ServiceToken: !ImportValue LambdaWaiter
      WaitSeconds: 750
  WaiterCustomResource1:
    Type: "AWS::CloudFormation::CustomResource"
    DependsOn: WaiterCustomResource
    DeletionPolicy: Retain
    Properties:
      ServiceToken: !ImportValue LambdaWaiter
      WaitSeconds: 750
  WaiterCustomResource2:
    Type: "AWS::CloudFormation::CustomResource"
    DependsOn: WaiterCustomResource1
    DeletionPolicy: Retain
    Properties:
      ServiceToken: !ImportValue LambdaWaiter
      WaitSeconds: 750
  WaiterCustomResource3:
    Type: "AWS::CloudFormation::CustomResource"
    DependsOn: WaiterCustomResource2
    DeletionPolicy: Retain
    Properties:
      ServiceToken: !ImportValue LambdaWaiter
      WaitSeconds: 750
  WaiterCustomResource4:
    Type: "AWS::CloudFormation::CustomResource"
    DependsOn: WaiterCustomResource3
    DeletionPolicy: Retain
    Properties:
      ServiceToken: !ImportValue LambdaWaiter
      WaitSeconds: 750
