AWSTemplateFormatVersion: '2010-09-09'
Description: FMS Security Groups usage audit policy update test.
Resources:
  PolicySGUsageAudit:
    Type: AWS::FMS::Policy
    Properties:
      ExcludeResourceTags: false
      PolicyName: PoicySGUsageAuditChanged
      RemediationEnabled: false
      ResourceType: AWS::EC2::SecurityGroup
      SecurityServicePolicyData:
        Type: SECURITY_GROUPS_USAGE_AUDIT
        ManagedServiceData: !Sub '{"type":"SECURITY_GROUPS_USAGE_AUDIT",
                                  "deleteUnusedSecurityGroups":false,
                                  "coalesceRedundantSecurityGroups":false,
                                  "optionalDelayForUnusedInMinutes":null}'
      DeleteAllPolicyResources: false
  WaiterCustomResource:
    Type: "AWS::CloudFormation::CustomResource"
    DeletionPolicy: Retain
    Properties:
      ServiceToken: !ImportValue LambdaWaiter
      WaitSeconds: 600
