AWSTemplateFormatVersion: '2010-09-09'
Description: FMS Security Groups usage audit policy create test.
Resources:
  PolicySGUsageAudit:
    Type: AWS::FMS::Policy
    Properties:
      ExcludeResourceTags: false
      PolicyName: PoicySGUsageAudit
      RemediationEnabled: false
      ResourceType: AWS::EC2::SecurityGroup
      SecurityServicePolicyData:
        Type: SECURITY_GROUPS_USAGE_AUDIT
        ManagedServiceData: !Sub '{"type":"SECURITY_GROUPS_USAGE_AUDIT",
                                  "deleteUnusedSecurityGroups":false,
                                  "coalesceRedundantSecurityGroups":false,
                                  "optionalDelayForUnusedInMinutes":null}'
      DeleteAllPolicyResources: false
